version: '3.6'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:ubuntu-6.2-latest
  ports:
   - "10051:10051"
  secrets:
   - zbx_dbpass
  environment:
   - DB_SERVER_HOST=zabbix-db
   - MYSQL_USER=root
   - MYSQL_PASSWORD_FILE=/run/secrets/zbx_dbpass
   - MYSQL_DATABASE=zabbix
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
  volumes:
   - /data/zabbix/zabbix-server:/var/lib/zabbix:rw
  networks:
   zabbix_db_zbx_backend:
     aliases:
      - zabbix-server
   zbx_frontend:
     aliases:
      - zabbix-server

 zabbix-web-apache-mysql:
  image: zabbix/zabbix-web-apache-mysql:ubuntu-6.2-latest
  ports:
   - "8081:8080"
   - "8443:8443"
  secrets:
   - zbx_dbpass
  environment:
   - DB_SERVER_HOST=zabbix-db
   - MYSQL_DATABASE=zabbix
   - MYSQL_USER=root
   - MYSQL_PASSWORD_FILE=/run/secrets/zbx_dbpass
   - ZBX_SERVER_HOST=zabbix-server
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 3
  depends_on:
   - zabbix-server
  networks:
   zabbix_db_zbx_backend:
   zbx_frontend:

 zabbix-agent:
  image: zabbix/zabbix-agent:ubuntu-6.2-latest
  ports:
   - "10050:10050"
  environment:
   - ZBX_SERVER_HOST=zabbix-server
  deploy:
   mode: global
  networks:
#   zbxagent_net:
    zabbix_db_zbx_backend:

networks:
#  zbxagent_net:
#    driver: overlay
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
  zbx_frontend:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"
  zabbix_db_zbx_backend:
    driver: overlay
    external: true
    driver_opts:
      com.docker.network.enable_ipv6: "false"

secrets:
  zbx_dbpass:
    external: true
