version: '3.6'

services:

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-6.2.0
    environment:
    - DB_SERVER_HOST=zabbix-db
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin
    - MYSQL_DATABASE=zabbix
    ports:
    - '10050:10050'
    - '10051:10051'
    volumes:
      - /data/zabbix:/var/lib/zabbix
    networks:
      monitoring_net: {}
    deploy:
       mode: replicated
       replicas: 1
       restart_policy:
         condition: on-failure
         delay: 5s
       placement:
         constraints: [node.role == worker]

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-6.2.0
    environment:
    - DB_SERVER_HOST=zabbix-db
    - MYSQL_DATABASE=zabbix
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin
    - ZBX_SERVER_HOST=zabbix-server
    ports:
    - '80:8080'
    networks:
      monitoring_net: {}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints: [node.role == worker]
    depends_on:
    - 'zabbix-server'

volumes:
  zabbix_data:
    driver: local

networks:
  monitoring_net:
    external: true
    name: monitoring_overlay
