version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:ubuntu-6.2-latest
  hostname: zabbix-server
  ports:
   - "10051:10051"
  environment:
   - DB_SERVER_HOST=mysql-server
   - MYSQL_USER=root
   - MYSQL_PASSWORD=admin
   - MYSQL_DATABASE=zabbix
   - ZBX_ENABLE_SNMP_TRAPS=true
   - ZBX_AUTONODEADDRESS=hostname
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
  volumes:
   - /data/zabbix/zabbix_server:/var/lib/zabbix:rw
  depends_on:
   - mysql-server
  networks:
   zbx_net_backend:
   zbx_net_frontend:

 zabbix-web-apache-mysql:
  image: zabbix/zabbix-web-apache-mysql:ubuntu-6.2-latest
  ports:
   - "8081:8080"
   - "8443:8443"
  environment:
   - DB_SERVER_HOST=mysql-server
   - MYSQL_DATABASE=zabbix
   - MYSQL_USER=root
   - MYSQL_PASSWORD=admin
   - ZBX_SERVER_HOST=zabbix-server
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 3
  depends_on:
   - mysql-server
   - zabbix-server
  networks:
   zbx_net_backend:
   zbx_net_frontend:

 zabbix-agent:
  image: zabbix/zabbix-agent:ubuntu-6.2-latest
  ports:
   - "10050:10050"
  environment:
   - ZBX_HOSTNAME=zabbix-server
   - ZBX_SERVER_HOST=zabbix-server
  deploy:
   mode: global
  networks:
<<<<<<< V1
   zbx_net_backend:

 mysql-server:
  image: mysql:8.0-oracle
  command:
   - mysqld
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
   - --default-authentication-plugin=mysql_native_password
  environment:
   - MYSQL_ROOT_PASSWORD=admin
   - MYSQL_DATABASE=zabbix
  volumes:
   - /data/zabbix/zabbix_db:/var/lib/mysql:rw
  networks:
   zbx_net_backend:

=======
#   zbxagent_net:
#    zabbix_db_zbx_backend:
    zbx_frontend:
>>>>>>> local
networks:
  zbx_net_frontend:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"
  zbx_net_backend:
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
